language: node_js
node_js:
  - "7"

before_script:
  - npm install

script:
  - npm run package

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "./dist/sfRTC.zip"
  skip_cleanup: true
  on:
    tags: true